### ISSUE TITLE
Dateien mit >50MB werden nicht archiviert

### ISSUE THREAD

**Issue by hf-kklein** [Hochfrequenz/edi_energy_mirror#7]
> remote: warning: GH001: Large files detected. You may want to try Git Large File Storage - https://git-lfs.github.com.
remote: warning: See http://git.io/iEPt8g for more information.
remote: warning: File edi_energy_de/past/EDI@EnergyAnwendungshilfezudenDatenformatenderMarktkommunikation202014-006_20181107_20171001.pdf is 51.15 MB; this is larger than GitHub's recommended maximum file size of 50.00 MB
remote: warning: File edi_energy_de/past/EDI@EnergyAnwendungshilfezudenDatenformatenderMarktkommunikation202014-007_99991231_20181108.pdf is 51.24 MB; this is larger than GitHub's recommended maximum file size of 50.00 MB
remote: warning: File edi_energy_de/past/EDI@EnergyAnwendungshilfezudenDatenformatenderMarktkommunikation202014-011_20190331_20181219.pdf is 51.07 MB; this is larger than GitHub's recommended maximum file size of 50.00 MB
remote: warning: File edi_energy_de/past/EDI@EnergyAnwendungshilfezudenDatenformatenderMarktkommunikation2020DerServicewirdabdem1.8.2019eingestellt._20190731_20190401.pdf is 51.19 MB; this is larger than GitHub's recommended maximum file size of 50.00 MB
To https://github.com/Hochfrequenz/edi_energy_mirror
   a3007a0..33827fd  master -> master

**Comment by hf-krechan** [comment]
I guess this is solved cause we have LFS now activated 
![image](https://github.com/user-attachments/assets/e48676fa-7651-4ad4-90a6-7891c6108917)
